/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SessionStats = IDL.Record({
  'totalCaloriesBurned' : IDL.Float64,
  'totalWeightLifted' : IDL.Float64,
  'totalSessions' : IDL.Nat,
});
export const WorkoutGoal = IDL.Variant({
  'weightLoss' : IDL.Null,
  'muscleGain' : IDL.Null,
  'generalHealth' : IDL.Null,
  'endurance' : IDL.Null,
});
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'weight' : IDL.Float64,
  'fitnessGoal' : WorkoutGoal,
  'name' : IDL.Text,
  'gender' : Gender,
});
export const ExerciseLog = IDL.Record({
  'weight' : IDL.Float64,
  'name' : IDL.Text,
  'reps' : IDL.Nat,
  'sets' : IDL.Nat,
  'caloriesBurned' : IDL.Float64,
  'metValue' : IDL.Float64,
});
export const WorkoutSession = IDL.Record({
  'date' : IDL.Text,
  'exercises' : IDL.Vec(ExerciseLog),
  'totalCalories' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllStatsSortedByCalories' : IDL.Func(
      [],
      [IDL.Vec(SessionStats)],
      ['query'],
    ),
  'getAllStatsSortedBySessionCount' : IDL.Func(
      [],
      [IDL.Vec(SessionStats)],
      ['query'],
    ),
  'getAllStatsSortedByTotalWeight' : IDL.Func(
      [],
      [IDL.Vec(SessionStats)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSessionStats' : IDL.Func([], [IDL.Opt(SessionStats)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorkoutSessions' : IDL.Func([], [IDL.Vec(WorkoutSession)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logWorkoutSession' : IDL.Func([IDL.Text, IDL.Vec(ExerciseLog)], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SessionStats = IDL.Record({
    'totalCaloriesBurned' : IDL.Float64,
    'totalWeightLifted' : IDL.Float64,
    'totalSessions' : IDL.Nat,
  });
  const WorkoutGoal = IDL.Variant({
    'weightLoss' : IDL.Null,
    'muscleGain' : IDL.Null,
    'generalHealth' : IDL.Null,
    'endurance' : IDL.Null,
  });
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'weight' : IDL.Float64,
    'fitnessGoal' : WorkoutGoal,
    'name' : IDL.Text,
    'gender' : Gender,
  });
  const ExerciseLog = IDL.Record({
    'weight' : IDL.Float64,
    'name' : IDL.Text,
    'reps' : IDL.Nat,
    'sets' : IDL.Nat,
    'caloriesBurned' : IDL.Float64,
    'metValue' : IDL.Float64,
  });
  const WorkoutSession = IDL.Record({
    'date' : IDL.Text,
    'exercises' : IDL.Vec(ExerciseLog),
    'totalCalories' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllStatsSortedByCalories' : IDL.Func(
        [],
        [IDL.Vec(SessionStats)],
        ['query'],
      ),
    'getAllStatsSortedBySessionCount' : IDL.Func(
        [],
        [IDL.Vec(SessionStats)],
        ['query'],
      ),
    'getAllStatsSortedByTotalWeight' : IDL.Func(
        [],
        [IDL.Vec(SessionStats)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSessionStats' : IDL.Func([], [IDL.Opt(SessionStats)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorkoutSessions' : IDL.Func([], [IDL.Vec(WorkoutSession)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logWorkoutSession' : IDL.Func([IDL.Text, IDL.Vec(ExerciseLog)], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };